spring:
  rabbitmq:
    host:
    exchange:
      verify: rsi-verify
      auth: rsi-auth
    queue:
      verify: rsi-verify.v1-send-verify
      auth: v1-auth-status
    routingkey: "#"
    password:
    username:
    virtual-host:
    ssl:
      enabled: true
basic-auth: ${BASICAUTH}
auth-url: ${AUTH_URL}
grant: ${GRANT}
scope: ${SCOPE}
com:
  scfleets:
    baseUrl: ${BASE_URL}
    pilotUri:
      updatePilotRsiProfile: ${UPDATE_PILOT_RSI_PROFILE_URI}
    accountUir:
      accountAuthById: ${ACCOUNT_AUTH_BY_ID_URI}
    spectrumClient:
      baseUrl: ${RSI_BASE_URL}
      messageUri: ${MESSAGE_URI}
      lobbyInfoUri: ${LOBBY_INFO_URI}
      autocompleteUri: ${AUTOCOMPLETE_URI}

